apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cluster-config
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/teehurme/devopswithkubernetes
  ref:
    branch: main
