apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- example-source.yaml
- example-gitopss-app.yaml
- cluster-config.yaml
- cluster-gitopss.yaml
